version: "3.8"
services:
  db:
    image: postgres:15-alpine
    container_name: grupo3_postgres
    restart: always
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password123
      POSTGRES_DB: sistema_reservas
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
